# src/main/resources/application-prod.properties

# Database PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# File Upload
file.upload-dir=/app/uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Server
server.port=${PORT:8080}

# Logging
logging.level.root=INFO
logging.level.com.ceremony.religious=INFO
logging.file.name=/app/logs/application.log

# Wave API
wave.api.url=${WAVE_API_URL}
wave.api.key=${WAVE_API_KEY}

# Orange Money API
orange.money.api.url=${ORANGE_MONEY_API_URL}
orange.money.merchant.key=${ORANGE_MONEY_MERCHANT_KEY}
orange.money.merchant.id=${ORANGE_MONEY_MERCHANT_ID}

# Callback URL
app.callback.url=${APP_CALLBACK_URL}