spring.application.name=demo
# Application
server.port=8086

# Active Profile
spring.profiles.active=dev

# Database - Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-hidden-credit-ad1380l5.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_otL5TYpb6VuS

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2KB

# File Storage
file.upload-dir=./uploads

# JWT Configuration
jwt.secret=VotreSecretTresSecurisePourJWT2024CeremonyReligieuse123456789
jwt.expiration=86400000

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin123

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# Wave API Configuration
wave.api.url=https://api.wave.com/v1
wave.api.key=your-wave-api-key-here

# Orange Money API Configuration
orange.money.api.url=https://api.orange.com/orange-money-webpay/dev/v1
orange.money.merchant.key=your-orange-merchant-key
orange.money.merchant.id=your-merchant-id

# Callback URL (doit être accessible publiquement en production)
app.callback.url=http://localhost:8080/api/payments/callback
# En production: app.callback.url=https://yourdomain.com/api/payments/callback

# Cloudinary Configuration
cloudinary.cloud-name=dvr66cxgj
cloudinary.api-key=349651835465745
cloudinary.api-secret=MPUQYSBGBbj0o0MTb8zp5-tRqf0