# Database - Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-hidden-credit-ad1380l5-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_otL5TYpb6VuS
spring.datasource.driver-class-name=org.postgresql.Driver

# File Storage Path
file.upload-dir=./uploads

# Logging
logging.level.com.ceremony.religious=DEBUG
logging.level.org.springframework.security=DEBUG